Python 3 fixes to graph-handling (Node.__lt__ and Subgraph.__lt__)
Python 3 changed how ordering works.  In particular, for instances of a
class to be sortable, the class needs at least a __lt__, or a
   TypeError: unorderable types
will be raised.

This led to the following tests failing with Python 3:
  tests/examples/lto
  tests/gccutils/graph

Provide the missing __lt__ methods