Avoid multiline warning strings in libcpychecker.formatstrings
When building with gcc 6, warnings emitted by
  libcpychecker.formatstrings.WrongNumberOfVars
showed some whitespace differences in the final " [-Werror]":

  ERROR: test_too_many_varargs (__main__.PyArg_ParseTupleAndKeywordsTests)
- [-Werror]
+    [-Werror]

I'm not sure exactly why this has started, but it seems error-prone to
be sending multiline strings through warning_at, so this patch standardizes
these warnings to emit just one line for the warning_at, and then print
the additional information to stderr via extra_info (), generalizing the
approach already used by MismatchingType.