implement verification of PyMethodDef tables
From the "Ideas for future tests", implement checking of PyMethodDef tables,
verifying that the signatures match the flags (by number of arguments, at
least).  Also, verify that they are NULL terminated.

This found an actual mismatch within the test suite, in:
  tests/cpychecker/refcounts/PyArg_ParseTupleAndKeywords/correct_O
with this error message:
  input.c:48:22: error: flags do not match callback signature for 'test' within PyMethodDef table
  input.c:48:22: note: expected ml_meth callback of type "PyObject (fn)(someobject *, PyObject *)" (2 arguments)
  input.c:48:22: note: actual type of underlying callback: struct PyObject * <Tc58> (struct PyObject *, struct PyObject *, struct PyObject *) (3 arguments)
  input.c:48:22: note: see http://docs.python.org/c-api/structures.html#PyMethodDef