cpychecker: rewrite CPython.steal_reference to use CPython.change_refcount
Rewrite CPython.steal_reference() to use CPython.change_refcount(), so that
it works in the same way as the other refcount-modifying functions (add_ref
etc)

Fixes a traceback seen when analyzing psycopg:

  psycopg/psycopgmodule.c: In function ‘init_psycopg’:
  psycopg/psycopgmodule.c:981:23: error: Unhandled Python exception raised calling 'execute' method
  ...
  KeyError: Region('connectionType.ob_refcnt')